<a href="https://colab.research.google.com/github/Antony6001/Uber-Eats-Banglore-Restaurant-Intelligence-/blob/main/json_file_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#orders dataset

In [8]:
#Required packages import

import pandas as pd
import numpy as np
import json

#data read

In [15]:
df=pd.read_json("/content/orders.json")

In [17]:
with open("/content/orders.json")as f:
  df=json.load(f)

In [18]:
df = pd.json_normalize(df)
print(df.head())

                               order_id          restaurant_name  order_date  \
0  8174c2af-07a4-4837-9068-1169d963e36e           TBC Sky Lounge  2025-05-06
1  0f9ddb57-4632-4a9f-9afe-1d2e41b94e32  KC Das - Sweet Paradise  2026-01-08
2  099deda6-8c53-41cb-abf8-00126e6b2643        Hotel Kadamba Veg  2026-01-22
3  94a6ba27-d6ef-4d10-a026-ac0c0afa8505            Cafe Srinidhi  2025-11-10
4  216f3ec7-80a9-4d95-872f-715c37163b6d                   Pebble  2025-12-22

   order_value discount_used payment_method
0       201.87            No           Card
1      1392.27            No           Cash
2      1358.35           Yes            UPI
3       782.37            No            UPI
4      1551.09           Yes            UPI

#Data Undersatnding

In [19]:
df.shape

(25000, 6)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         25000 non-null  object
 1   restaurant_name  25000 non-null  object
 2   order_date       25000 non-null  object
 3   order_value      25000 non-null  float64
 4   discount_used    25000 non-null  object
 5   payment_method   25000 non-null  object
dtypes: float64(1), object(5)
memory usage: 1.1+ MB

In [23]:
df.head()

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method
0,8174c2af-07a4-4837-9068-1169d963e36e,TBC Sky Lounge,2025-05-06,201.87,No,Card
1,0f9ddb57-4632-4a9f-9afe-1d2e41b94e32,KC Das - Sweet Paradise,2026-01-08,1392.27,No,Cash
2,099deda6-8c53-41cb-abf8-00126e6b2643,Hotel Kadamba Veg,2026-01-22,1358.35,Yes,UPI
3,94a6ba27-d6ef-4d10-a026-ac0c0afa8505,Cafe Srinidhi,2025-11-10,782.37,No,UPI
4,216f3ec7-80a9-4d95-872f-715c37163b6d,Pebble,2025-12-22,1551.09,Yes,UPI

In [20]:
df.columns

Index(['order_id', 'restaurant_name', 'order_date', 'order_value',
       'discount_used', 'payment_method'],
      dtype='object')

#Data cleaning

Missing values find and handle

In [24]:
for col in df.columns:
  miss=df[col].isnull().sum()
  print(f"{col}:{miss}")

order_id:0
restaurant_name:0
order_date:0
order_value:0
discount_used:0
payment_method:0

In [26]:
df.restaurant_name

0                 TBC Sky Lounge
1        KC Das - Sweet Paradise
2              Hotel Kadamba Veg
3                  Cafe Srinidhi
4                         Pebble
                  ...
24995                   Carnatic
24996         Reddy's Restaurant
24997       BTM Bawarchi Biryani
24998                   Nite Out
24999                  Zee5 Loft
Name: restaurant_name, Length: 25000, dtype: object

In [27]:
df.restaurant_name = df.restaurant_name.str.lower()

In [28]:
df.restaurant_name=df.restaurant_name.str.strip()

In [29]:
df.restaurant_name=df.restaurant_name.str.replace("-","")

In [30]:
df['restaurant_name'] = df['restaurant_name'].str.replace(r'[^a-zA-Z\s]', '', regex=True)

In [31]:
df.restaurant_name.value_counts()

restaurant_name
caf morish                               29
khan saheb grills and rolls              25
caf secret alley                         25
nh                                       24
mums kitchen                             22
                                         ..
navami                                    1
swathi maharaja                           1
the hub  the bar  hotel ramada encore     1
the barn  bar  kitchen                    1
  the oterra                              1
Name: count, Length: 3132, dtype: int64

In [34]:
df.order_date

0        2025-05-06
1        2026-01-08
2        2026-01-22
3        2025-11-10
4        2025-12-22
            ...
24995    2025-11-24
24996    2025-06-24
24997    2025-12-04
24998    2025-09-21
24999    2025-08-07
Name: order_date, Length: 25000, dtype: object

In [35]:
import datetime

In [41]:
df['order_date']=pd.to_datetime(df['order_date'],errors='coerce')

In [42]:
df['order_value']

0         201.87
1        1392.27
2        1358.35
3         782.37
4        1551.09
          ...
24995    1254.91
24996     760.39
24997     707.99
24998     724.29
24999     905.00
Name: order_value, Length: 25000, dtype: float64

In [45]:
df.order_value.describe()

count    25000.000000
mean       986.081873
std        472.948544
min        150.050000
25%        589.602500
50%        966.475000
75%       1344.772500
max       1999.840000
Name: order_value, dtype: float64

In [46]:
df.discount_used

0         No
1         No
2        Yes
3         No
4        Yes
        ...
24995     No
24996     No
24997    Yes
24998    Yes
24999     No
Name: discount_used, Length: 25000, dtype: object

In [47]:
df.discount_used.value_counts()

discount_used
No     12509
Yes    12491
Name: count, dtype: int64

In [49]:
df.discount_used=df.discount_used.str.lower()

In [ ]:
df.payment_method.value_counts()

payment_method
Cash    8384
Card    8364
UPI     8252
Name: count, dtype: int64

In [52]:
df.payment_method=df.payment_method.str.lower()

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         25000 non-null  object
 1   restaurant_name  25000 non-null  object
 2   order_date       25000 non-null  datetime64[ns]
 3   order_value      25000 non-null  float64
 4   discount_used    25000 non-null  object
 5   payment_method   25000 non-null  object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 1.1+ MB

In [54]:
df.head()

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method
0,8174c2af-07a4-4837-9068-1169d963e36e,tbc sky lounge,2025-05-06,201.87,no,card
1,0f9ddb57-4632-4a9f-9afe-1d2e41b94e32,kc das sweet paradise,2026-01-08,1392.27,no,cash
2,099deda6-8c53-41cb-abf8-00126e6b2643,hotel kadamba veg,2026-01-22,1358.35,yes,upi
3,94a6ba27-d6ef-4d10-a026-ac0c0afa8505,cafe srinidhi,2025-11-10,782.37,no,upi
4,216f3ec7-80a9-4d95-872f-715c37163b6d,pebble,2025-12-22,1551.09,yes,upi

In [ ]:
df.to_csv("orders.csv")