<a href="https://colab.research.google.com/github/Antony6001/Uber-Eats-Banglore-Restaurant-Intelligence-/blob/main/uber_eats_bangalore_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Uber Eats Restaurent Bangaluru intelligence & decision support system

In [51]:
#Required pakages
import pandas as pd
import numpy as np

In [52]:
#read the dataset

df=pd.read_csv('/content/Uber_Eats_data.csv')

#dataset understanding

In [4]:
df.head()

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

In [15]:
print(df.shape)

(23193, 13)

In [16]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         23193 non-null  object
 1   online_order                 23193 non-null  object
 2   book_table                   23193 non-null  object
 3   rate                         23193 non-null  object
 4   votes                        23193 non-null  int64
 5   phone                        23193 non-null  object
 6   location                     23193 non-null  object
 7   rest_type                    23193 non-null  object
 8   dish_liked                   23193 non-null  object
 9   cuisines                     23193 non-null  object
 10  approx_cost(for two people)  23193 non-null  object
 11  listed_in(type)              23193 non-null  object
 12  listed_in(city)              23193 non-null  object
dtypes: int64(1), object(12)
memory usage: 2.3+ MB
None

#step:1 data_cleaning

1.missing value cheking

In [37]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'phone',
       'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [38]:
for col in df.columns:
    missing_count = df[col].isnull().sum()
    print(f"{col}: {missing_count}")

name: 0
online_order: 0
book_table: 0
rate: 0
votes: 0
phone: 0
location: 0
rest_type: 0
dish_liked: 0
cuisines: 0
approx_cost(for two people): 0
listed_in(type): 0
listed_in(city): 0

2.datatype checking

In [39]:
for col in df.columns:
    print(f"{col}: {df[col].dtype}")

name: object
online_order: object
book_table: object
rate: object
votes: int64
phone: object
location: object
rest_type: object
dish_liked: object
cuisines: object
approx_cost(for two people): object
listed_in(type): object
listed_in(city): object

In [40]:
df['name'] = df['name'].str.encode('latin1', errors='ignore').str.decode('utf-8', errors='ignore')

In [41]:
# for removing unwanted charecters in name column

import re

df['name'] = df['name'].apply(lambda x: re.sub(r'[^a-zA-Z0-9 &]', '', x))

In [42]:
# converting the uppercase to lower_case

df.name=df.name.str.lower().str.replace('_',' ')

In [94]:
df.online_order=df.online_order.str.lower().str.replace(' ','_')

In [ ]:
df.book_table.value_counts()

book_table
No     17071
Yes     6122
Name: count, dtype: int64

In [88]:
df.book_table=df.book_table.str.lower()

In [ ]:
import ast

In [89]:
# convert the NEW (str) to numeric

df['rate']=df['rate'].replace(['NEW',None])

/tmp/ipykernel_1214/3011975050.py:3: FutureWarning: Series.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  df['rate']=df['rate'].replace(['NEW',None])

In [90]:
#Removing the "/5" , and dtype is changed here ,

df['rate']=df['rate'].str.replace('/5','').astype(float)

In [92]:
df.votes.dtype

dtype('int64')

In [ ]:
df.phone=df.phone.str.replace(r'\D','',regex=True)

In [ ]:
df['mobile'] = df['phone'].str[-10:]

In [ ]:
df['landline'] = df['phone'].str[:-10]

In [ ]:
df['landline'] = df['landline'].str.replace('^91', '', regex=True)

In [ ]:
df['mobile'] = df['phone'].str.extract(r'(\d{10})$')

In [ ]:

df.mobile=df.mobile.astype(int)

In [ ]:
df['landline'] = pd.to_numeric(df['landline'], errors='coerce')

In [12]:
# upper case to convert the lower case

df.location=df.location.str.lower().str.replace(' ','_')

In [14]:
df.location.value_counts()

location
koramangala_5th_block    1783
btm                      1456
indiranagar              1350
hsr                      1162
jayanagar                1037
                         ...
kanakapura_road             2
west_bangalore              2
yelahanka                   2
magadi_road                 2
kr_puram                    1
Name: count, Length: 88, dtype: int64

In [ ]:
df.location.describe()

count                     23193
unique                       88
top       koramangala_5th_block
freq                       1783
Name: location, dtype: object

In [ ]:
df.rest_type

0              Casual Dining
1              Casual Dining
2        Cafe, Casual Dining
3                Quick Bites
4              Casual Dining
                ...
23188     Bar, Casual Dining
23189       Fine Dining, Bar
23190     Casual Dining, Bar
23191     Casual Dining, Bar
23192                    Bar
Name: rest_type, Length: 23193, dtype: object

In [ ]:
df.rest_type=df.rest_type.str.lower().str.replace(' ','')

In [ ]:
df.rest_type.value_counts()

rest_type
casualdining               7349
quickbites                 5240
cafe                       2325
dessertparlor              1076
casualdining,bar            984
                           ...
finedining,microbrewery       5
club,casualdining             4
dessertparlor,kiosk           2
dhaba                         1
foodcourt,casualdining        1
Name: count, Length: 73, dtype: int64

In [ ]:
df.rest_type.describe()

count            23193
unique              73
top       casualdining
freq              7349
Name: rest_type, dtype: object

In [54]:
df.dish_liked=df.dish_liked.str.lower()

In [55]:
df.dish_liked

0        pasta, lunch buffet, masala papad, paneer laja...
1        momos, lunch buffet, chocolate nirvana, thai g...
2        churros, cannelloni, minestrone soup, hot choc...
3                                              masala dosa
4                                      panipuri, gol gappe
                               ...
23188    beer, chicken guntur, paneer tikka, fish, nood...
23189                                     rooftop ambience
23190    salads, coffee, breakfast buffet, halwa, chick...
23191                                 biryani, andhra meal
23192                         cocktails, pizza, buttermilk
Name: dish_liked, Length: 23193, dtype: object

In [ ]:

df.dish_liked.value_counts()

dish_liked
biryani                                                                                     181
chicken_biryani                                                                              73
friendly_staff                                                                               69
waffles                                                                                      68
paratha                                                                                      57
                                                                                           ...
tandoori_chicken,_mutton_biryani,_butter_chicken                                              1
coffee,_raj_kachori,_idli,_vada,_tea,_masala_dosa,_chaat                                      1
masala_dosa,_filter_coffee,_curd_rice                                                         1
dal_makhani,_galauti_kebab,_dum_biryani,_rasgulla,_fish,_garlic_kheer,_tandoori_broccoli      1
watermelon_juice,_malai_kulfi                                                                 1
Name: count, Length: 5189, dtype: int64

In [56]:

df.dish_liked.describe()

count       23193
unique       5189
top       biryani
freq          181
Name: dish_liked, dtype: object

In [59]:
df.cuisines

0                     north indian, mughlai, chinese
1                        chinese, north indian, thai
2                             cafe, mexican, italian
3                         south indian, north indian
4                           north indian, rajasthani
                            ...
23188       north indian, continental, mediterranean
23189                                    finger food
23190             chinese, continental, north indian
23191    andhra, south indian, chinese, north indian
23192                                    finger food
Name: cuisines, Length: 23193, dtype: object

In [58]:
df.cuisines=df.cuisines.str.strip()
df.cuisines=df.cuisines.str.lower()
df.cuisines=df.cuisines.str.replace('_','')

In [60]:
df['cuisines']=df['cuisines'].str.title()

In [ ]:
df.cuisines.value_counts()

cuisines
North Indian                           1144
North Indian, Chinese                   777
South Indian                            359
Cafe                                    273
South Indian, North Indian, Chinese     233
                                       ...
Tibetan, Nepalese                         1
South Indian, Chettinad                   1
Andhra, Hyderabadi, Biryani               1
Andhra, North Indian, South Indian        1
Thai, Chinese, Momos                      1
Name: count, Length: 1687, dtype: int64

In [63]:
df.cuisines.describe()

count            23193
unique            1687
top       North Indian
freq              1144
Name: cuisines, dtype: object

In [66]:
df['approx_cost(for two people)']=df['approx_cost(for two people)'].str.replace(',','')

In [69]:
df['approx_cost(for two people)']=df['approx_cost(for two people)'].astype(float)

In [73]:
df['approx_cost(for two people)'].describe()

count    23193.000000
mean       755.904368
std        521.448320
min         40.000000
25%        400.000000
50%        600.000000
75%       1000.000000
max       6000.000000
Name: approx_cost(for two people), dtype: float64

In [74]:
df['listed_in(type)']

0               Buffet
1               Buffet
2               Buffet
3               Buffet
4               Buffet
             ...
23188    Pubs and bars
23189    Pubs and bars
23190    Pubs and bars
23191    Pubs and bars
23192    Pubs and bars
Name: listed_in(type), Length: 23193, dtype: object

In [75]:
df['listed_in(type)']=df['listed_in(type)'].str.lower().str.replace(' ','')

In [76]:
df['listed_in(type)'].unique()

array(['buffet', 'cafes', 'delivery', 'desserts', 'dine-out',
       'drinks&nightlife', 'pubsandbars'], dtype=object)

In [77]:
df['listed_in(type)'].value_counts()

listed_in(type)
delivery            10625
dine-out             8009
desserts             1333
cafes                1047
drinks&nightlife      890
buffet                762
pubsandbars           527
Name: count, dtype: int64

In [78]:
df['listed_in(type)'].describe()

count        23193
unique           7
top       delivery
freq         10625
Name: listed_in(type), dtype: object

In [81]:

df['listed_in(city)']=df['listed_in(city)'].str.lower().str.replace(' ','')

In [82]:
df['listed_in(city)'].describe()

count     23193
unique       30
top         btm
freq       1423
Name: listed_in(city), dtype: object

In [83]:
df.head()

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"pasta, lunch buffet, masala papad, paneer laja...","North Indian, Mughlai, Chinese",800.0,buffet,banashankari
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"momos, lunch buffet, chocolate nirvana, thai g...","Chinese, North Indian, Thai",800.0,buffet,banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","churros, cannelloni, minestrone soup, hot choc...","Cafe, Mexican, Italian",800.0,buffet,banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,masala dosa,"South Indian, North Indian",300.0,buffet,banashankari
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"panipuri, gol gappe","North Indian, Rajasthani",600.0,buffet,banashankari

In [84]:
df.shape

(23193, 13)

In [85]:
df.drop(['phone'],axis=1,inplace=True)

In [86]:
df.shape

(23193, 12)

In [95]:
df.head()

,name,online_order,book_table,rate,votes,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,yes,yes,4.1,775,Banashankari,Casual Dining,"pasta, lunch buffet, masala papad, paneer laja...","North Indian, Mughlai, Chinese",800.0,buffet,banashankari
1,Spice Elephant,yes,no,4.1,787,Banashankari,Casual Dining,"momos, lunch buffet, chocolate nirvana, thai g...","Chinese, North Indian, Thai",800.0,buffet,banashankari
2,San Churro Cafe,yes,no,3.8,918,Banashankari,"Cafe, Casual Dining","churros, cannelloni, minestrone soup, hot choc...","Cafe, Mexican, Italian",800.0,buffet,banashankari
3,Addhuri Udupi Bhojana,no,no,3.7,88,Banashankari,Quick Bites,masala dosa,"South Indian, North Indian",300.0,buffet,banashankari
4,Grand Village,no,no,3.8,166,Basavanagudi,Casual Dining,"panipuri, gol gappe","North Indian, Rajasthani",600.0,buffet,banashankari

Duplicate checking

In [100]:
df.duplicated().sum()

np.int64(41)

In [101]:
df=df.drop_duplicates()

In [102]:
df.duplicated().sum()

np.int64(0)

In [104]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'location',
       'rest_type', 'dish_liked', 'cuisines', 'approx_cost(for two people)',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [103]:
df.shape

(23152, 12)

In [110]:

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23152 entries, 0 to 23192
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         23152 non-null  object
 1   online_order                 23152 non-null  object
 2   book_table                   23152 non-null  object
 3   rate                         23152 non-null  float64
 4   votes                        23152 non-null  int64
 5   location                     23152 non-null  object
 6   rest_type                    23152 non-null  object
 7   dish_liked                   23152 non-null  object
 8   cuisines                     23152 non-null  object
 9   approx_cost(for two people)  23152 non-null  float64
 10  listed_in(type)              23152 non-null  object
 11  listed_in(city)              23152 non-null  object
dtypes: float64(2), int64(1), object(9)
memory usage: 2.3+ MB

In [ ]:
df.to_csv('cleaned_data_fixed.csv', index=False, quoting=1)

In [ ]:
df.to_csv('cleaned_data.csv', index=False, encoding='utf-8',quoting=1)

In [106]:
import os

In [107]:
print(os.getcwd())

/content